### ISSUE TITLE
Using with transformers repository

### ISSUE THREAD

**Issue by normalOne95** [QData/TextAttack#222]
Hi,

Thanks for developing this great repo!!

I just want to ask how can I make this work with models trained with huggingface's transformers repository. I understand the models can be used directly (*bin file), but `textattack` needs `train_args.json` file also which is not provided with a transformers model.

How can I use models in transformers repo with textattack, or Do I have to train models with textattack only?

Edit: I see there are two args to load custom models, `--model-from-file` and `--model-from-huggingface`. Can you provide example of how to use these two arguments? Or point me to any example in docs? 

If I provide path to downloaded model in `--model-from-file`, I get the error:
`ValueError: Failed to import file`. 

Thanks,

**Comment by jxmorris12** [comment]
Hi @normalOne95 --

Ok, so ideally eventually we'll be able to support everything via `--model`. And regardless, this distinction between `--model`, `--model-from-file`, and `--model-from-huggingface` should be clearer in the documentation. Here's a quick explanation:
1. `--model` allows you to load textattack pre-trained models, either ones that we trained (which will be downloaded) or ones you trained (which will be loaded from disk)
2. `--model-from-file` allows you to write a short python script that loads your model & tokenizer and loads the model by dynamically importing that script. This gives you total flexibility over model loading. 
3. `--model-from-huggingface` loads models from the huggingface model repository (https://huggingface.co/models)

Either [2] or [3] seems best for your use case. [1] loads models from disk, but assumes they were trained using textattack (which is why we assume `train_args.json` exists). 

If you wanted to use [2], you could create a file like `mymodel.py` that loads your model:

```
model = load_my_model()
tokenizer = load_my_tokenizer()
```

Then, `textattack attack --model-from-file mymodel.py` should load your model properly. Let me know if that works for you or if you need more info.

Btw, how did you train the model using huggingface? Just wondering.

**Comment by normalOne95** [comment]
Hi @jxmorris12 ,

Thank you for the reply!! Makes sense now. I will try what you suggested.

1. I trained huggingface models using `run_glue.py` script provided with `transformers` repo. 

2. Another quick question, what is the use of module `bert_for_classification.py`. Is it possible that a Bert model based recipe does not call this module to make predictions, and just uses underlying HF transformers `model_class` for calling `forward`?

Thanks again,

**Comment by jxmorris12** [comment]
Hi @normalOne95 -- that's just a wrapper for BERT models. It's really not necessary since we just added this whole model wrapper idea (let me know if you need to know more about that too). I'll make a note to get rid of `bert_for_classification.py` eventually.
