### ISSUE TITLE
No effect of increased batch size.

### ISSUE THREAD

**Issue by normalOne95** [QData/TextAttack#245]
Hi,

I have tried increasing the `batch_size` for `textattack attack` command with the argument `--model-batch-size`, but this does not affect anything - neither the GPU used memory increases, and neither does the total speed of attack on the dataset increase.

Have you noticed anything similar? 
Thanks,

**Comment by jxmorris12** [comment]
Thanks @normalOne95 -- this is probably an issue with our new 'model wrappers' feature – specifically, that the batch size from argparse isn't passed in when we initialize a model wrapper. we're going to investigate and get back to you shortly

**Comment by jxmorris12** [comment]
Hi @normalOne95 -- I just ran a few test, and batch size seems to work for me, at least for PyTorch (and HuggingFace) models. You likely didn't see an increase in usage because batch size is very seldomly a bottleneck. Most steps of most attacks make only few queries– maybe 20 or so. 

If you set the batch size to something really small (say, 2) you should see a change in GPU usage.

That said, unfortunately, the runtime doesn't very much with the model batch size. The slow step is usually the application of constraints.
