### ISSUE TITLE
ValueError: Cannot perform GradientBasedWordSwap on model BertForSequenceClassification

### ISSUE THREAD

**Issue by normalOne95** [QData/TextAttack#256]
Hi,

I am getting the following error when I try and run `BERT-base` for `hotflip` attack. 

```
raise ValueError(f"Cannot perform GradientBasedWordSwap on model {model}.")
ValueError: Cannot perform GradientBasedWordSwap on model BertForSequenceClassification(
```
in `File text_attack/textattack/shared/validators.py", line 88, in validate_model_gradient_word_swap_compatibility`

The reason provided for this is 
`We can only take the gradient with respect to an individual word if the model uses a word-based tokenizer.` 

Why should this be true though? Can't we still replace the subwords (from BERT tokenizer) even if they might not make sense in some cases?

Thanks,

**Comment by jxmorris12** [comment]
Hi @normalOne95 -- we've talked about this a bit with the team. HotFlip only defines its attacks (in the paper) wrt word-based models, so we try to catch and throw an error if the model doesn't use word-level tokenization.

That said, we'd love to have this feature. Ideally we'd have three versions of HotFlip for subwords:
- your version: replace subwords with other subwords
- the BAE attack version: replace only full words with other full words
- the BERTAttack attack version: replace full words, but also do subword expansion to try to find full words to replace from subwords

Let us know if you are interested in helping develop this! It is a tiny bit trickier, since we'd also want to establish a protocol for getting gradients from model wrappers in a framework agnostic way. (For example, adding `get_grads()` function to the `ModelWrapper` class, or something like that.)

**Comment by lethaiq** [comment]
@jxmorris12 do we have any specific reasons that we also do not allow CNN with hotflip? As far as I can see from the code we only allow LSTM for hotflip attack? 

As for this reason, should we have a better mechanism to manage the compatibility between attack recipe and model type?

**Comment by jxmorris12** [comment]
You're right that HotFlip as defined should work fine with the CNN. We just have to implement it. 

What is wrong with how we manage attack-model compatibility currently?

**Comment by lethaiq** [comment]
> You're right that HotFlip as defined should work fine with the CNN. We just have to implement it.
> 
> What is wrong with how we manage attack-model compatibility currently?

I just checked the repository and seem like the repo is using MODELS_BY_GOAL_FUNCTIONS to check the compatibility between goal functions and the target model. Can we also have another global variable (e.g., MODELS_BY_TRANSFORMATION) to check the compatibility between transformation (e.g., WordSwapGradientBased) with the target model?

I just wonder if there is a better way to manage these as right now if someone has a new or external model, they would need to record the model into these variables inside the core code. How about we have some class-level compatibility flag for each model's type (e.g., BERTForClassification, LSTMForClassification).

**Comment by donggrant** [comment]
It seems like the original issue/question you presented has been resolved. If you would or anyone else would like to pursue this enhancement for adding class-level flags, a PR can be created for that.
