### ISSUE TITLE
Support classification functions for MORPHEUS

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#261]
After adding morpheus (see issue #181), we need the recipe to support goal functions for classification tasks. Should be a quick change.

**Comment by samsontmr** [comment]
Quick comment: for classification/extractive QA, the loss (instead of the accuracy/F1) should be used to guide the search where possible.

Are the classification attack recipes meant to be used for attacks on extractive QA tasks like SQuAD? The loss function for such tasks is a variation of the standard CE loss. [Example QA loss from my implementation here.](https://github.com/salesforce/morpheus/blob/ef084cd2bab8b83e573ecd1f657bcde222ee76e3/morpheus/morpheus_qa.py#L109)
