### ISSUE TITLE
Preserving pre-tokenized word boundaries

### ISSUE THREAD

**Issue by Mrpatekful** [QData/TextAttack#295]
Sorry for filling an issue for this, but the slack link is expired and I couldn't find a different of platform for this project to ask my question.

I am trying to apply TextAttack to named entity recognition, however most of tagging tasks like NER have datasets that rely on pre-tokenized texts. By having a quick glance at the documentation and the source code, TextAttack does not accept pre-defined word boundaries, but it computes them internally. My question is, is there a less painful way to incorporate such behaviour into the framework, like instead passing a simple string of text such as `"How are you?"` to the `augment()` method, passing it as list of tokens `["How", "are", "you", "?"]`.

**Comment by jxmorris12** [comment]
Thanks for letting us know about the Slack link! Not sure what happened there, but I updated the link, so we should be good to go. Join us via the new link!

I'm not sure if providing a list of tokens is the best solution since TextAttack internally wouldn't always know how to recreate the input string from the tokens. I think that we should support passing a custom tokenization function instead of the default `words_from_text` thing we have going now.

We're actually working on this specific problem since it relates to how we can improve TextAttack to work for different languages. Hopefully we can add this soon!

As for your specific question, could you just join the text with spaces and pass it in that way? Or are you worried that TextAttack's tokenization may slightly differ from the dataset's, which could affect model performance?

**Comment by Mrpatekful** [comment]
Well, yes my problem is that in most cases the tokenizer for these tagging datasets is not known, therefore joining the text and then tokenizing it again might lose the original alignment of tokens and their labels.

But even if assuming that the tokenizer is available, and I can restore the original sequence to have the correct alignment for each token with its corresponding token tag, I don't think this is the best solution for this problem. It really feels like I am trying to use something in a way it wasn't meant to. Considering that multiple properties or tags can apply to a particular word, or more generally to a snippet of a string, it is not ideal for me to separate this information.

I might actually end up implementing my ideal solution by a fork of this project, where a Spacy-like `Doc` data structure is used to store the input text to be attacked, which allows me to keep the pairing of textual data and its properties of specific tokens.
