### ISSUE TITLE
Word embedding in other languages

### ISSUE THREAD

**Issue by Ges00** [QData/TextAttack#370]
Hi, i really appriciate your effort in the making of this amazing library! I've been using it to create word embedding on different english datasets and now i'd l'ike to use it for an italian dataset. 
Is it possible to use this library to apply word embedding with text data written in a language different from english, like italian?

Thanks.

**Comment by Tambup** [comment]
Hi, i work together with @Ges00. We are trying to make some attacks to models for italian dataset. 
So, we'd like to use WordEmbedding class for the data augmentation phase.
We saw the static method "counterfitted_GLOVE_embedding".
So, our problem is to create the following files (given an italian word embedding) consistently with the use across the library:
word_embeddings_file,  word_list_file, mse_dist_file, cos_sim_file, nn_matrix_file.
Can anyone suggest if there is a library that you used for, or some indications about how to?

We also appreciate very much to share our results in this repo if those can help grow this fantastic tool.

Thanks.

**Comment by jinyongyoo** [comment]
Hi @Ges00 and @Tambup. 

Yes, we do support use of the custom word embeddings. First off, `counterfitted_GLOVE_embedding` method is used to load an English GLOVE word embedding that TextAttack uses as default. It's not really designed to be used to load custom word embedding.

To create your own custom word embedding, you could create a `WordEmbedding` object with the following arguments:
-  `embedding_matrix`: This is a  2-D array of shape N x D where N represents size of vocab and D is the dimension of embedding vectors. It can either be a numpy ndarray or a torch tensor.
- `word2index`: This is a dictionary (or an object that behaves like a dictionary) that maps words to their respective index of the `embedding_matrix`. So if word "hello" is suppose to be the fifth word in the `embedding_matrix`, the dictionary would have the following key-value: `"hello": 5`. 
- `index2word`: This is also a dictionary (or an object that behaves like a dictionary) that does the reverse and map each index of the dictionary to the word it represents.
- `nn_matrix`: This is a matrix of precomputed nearest neighbors of each word. Neighbors are represented by their index. It should be a 2-D integer array of shape N x K where N represents size of vocab and K is the top-K nearest neighbors. While this argument is optional, this is helpful for cases where you need to calculate nearest neighbors repeatedly since it saves computation. 

Once you create the `WordEmbedding` object, you can pass it to `WordSwapEmbedding` transformation or `WordEmbeddingDistance` constraint!

Let me know if you have any more questions.

**Comment by Tambup** [comment]
Thanks a lot @jinyongyoo. We start to work in this direction.

**Comment by Tambup** [comment]
@Ges00 close this issue. Is solved.
