### ISSUE TITLE
How to accelerate attack in parallel through API

### ISSUE THREAD

**Issue by ziqi-zhang** [QData/TextAttack#372]
Hi,

I'm developing my project with TextAttack API. I wonder how can I parallel the attack to accelerate? Here is the current code I'm using:
```
    
    model_wrapper = textattack.models.wrappers.HuggingFaceModelWrapper(
        model, tokenizer, batch_size=args.model_batch_size
    )
    recipe = PWWSRen2019.build(model_wrapper)
    
    for idx, result in enumerate(recipe.attack_dataset(dataset)):
        
        print(("-" * 20), f"Result {idx+1}", ("-" * 20))
        print(result.__str__(color_method="ansi"))
        print()
        if idx > 100:
            break
```
The code returns one result at one time in the loop. Because I want to check the overall performance of the whole dataset so I only care the accuracy. How can I make full use of the GPU memory and accelerate the process? It seems the batch_size of model_wrapper does not help.

Thanks

**Comment by jinyongyoo** [comment]
Good question! If you have multiple GPUs and want to parallelize attacks, you can run your attacks via [command line](https://textattack.readthedocs.io/en/latest/1start/command_line_usage.html) and set the flag `--parallel`. Now, we don't offer a way to parallelize attacks on the API level yet. If you really wish to parallelize on the API level, you could try to replicate the code we have for command line parallelism (https://github.com/QData/TextAttack/blob/master/textattack/commands/attack/run_attack_parallel.py).

High level explanation is that we start a pool or worker processes and have each worker process run an attack and output the result, and we communicate the inputs and outputs with the main process via a shared queue. 

Let me know if you have more questions.

**Comment by ziqi-zhang** [comment]
@jinyongyoo Thanks for your detailed reply! I want to parallelize attacks on one GPU because the memory occupation of 1 sentence is low. Is it viable to use run_attack_parallel.py to run multiple attacks on one GPU at the same time?

**Comment by jinyongyoo** [comment]
I have personally ran two attacks on one GPU, so yes it is possible. What you can do is instead of creating a worker process per GPU (as in https://github.com/QData/TextAttack/blob/82e8f51c9038f8d7b14d116c162039f321ea6bdb/textattack/commands/attack/run_attack_parallel.py#L136), create as many you need and then manually fix the `gpu_id` of each worker process.

**Comment by lethaiq** [comment]
@jinyongyoo This is very helpful. Can we deploy this as an additional argument to control this behavior?

**Comment by jinyongyoo** [comment]
Do you mean on the CLI level or on the API level (e.g. via `attack_dataset`). Either way if you would like to make a PR to add it as a new feature, I'll be more than happy to review it.

**Comment by Opdoop** [comment]
Thanks, @jinyongyoo.😀 I'm new to multiprocess and I have one question. If I have multiple GPU, how to run two attacks on each GPU as you do?

**Comment by jinyongyoo** [comment]
@Opdoop I think you could just create `2*num_gpu` worker processes and the code should assign two processes to each GPUs. But I'm not 100% certain so you might have to do some hard coding. 

As a side note, I think we will move towards attending parallel processing as a feature in the API level.

**Comment by Opdoop** [comment]
@jinyongyoo Thanks! Create `2*num_gpu` works, but the speed seems just like `num_gpu` process. I'm wondering why increasing the worker per gpu didn't change the attack speed.

**Comment by jinyongyoo** [comment]
@Opdoop For me, 2*num_gpu was a little bit faster, but not by much. It might just be that having more process and another process on the same gpu causes some overhead that limits how much performance gain we can achieve. 

@lethaiq , @Opdoop, @ziqi-zhang I've actually been working on TextAttack to make attacking on the API level easier. It's still on a draft stage, but if you guys are interested in trying it out, you can checkout this branch https://github.com/QData/TextAttack/tree/attack-api and install from source. It probably has some bugs and issues that needs to be addressed before it can be merged and released, so I would appreciate if you guys try it out and give some feedback.

The main change is introducing ``Attacker`` class and ``AttackArgs``. ``AttackArgs`` is a dataclass that lets users define the arguments for attacks (similar to https://huggingface.co/transformers/main_classes/trainer.html#trainingarguments). ``Attacker`` takes in ``Attack``, ``textattack.datasets.Dataset``, and ``AttackArgs`` objects to perform attacks on the datasets with the same features for logging and saving checkpoints as the command line version, bringing some parity between API-level usage and command-line usage. 

Now, for parallel processing, taking in any user defined ``Attack`` and performing parallel attacks is tricky because we need to serialize the ``Attack`` object using ``pickle`` module to share it between processes. This is slow and difficult, so one workaround is to require users to pass in a zero-argument callable that returns the desired ``Attack``. This way, we can call the function to newly initialize the attack in each worker process. You can checkout the example in https://github.com/QData/TextAttack/blob/attack-api/examples/attack/parallel_attack.py.

I'll make a draft PR for this branch. If you find any issues or have any comments, please leave make it there (instead of the main Github issues).

**Comment by lethaiq** [comment]
@jinyongyoo this is definitely very helpful. I will try to have a look. Thanks for the works.

**Comment by Opdoop** [comment]
@jinyongyoo Thanks! By the way, have you ever seen `segmentation fault (core dumped)` when using parallel attack on large dataset?

**Comment by jinyongyoo** [comment]
@Opdoop No I have not seen seg faults so far. When do you see that happening?

**Comment by Opdoop** [comment]
@jinyongyoo  When I try to attack the entire dataset, `segmentation fault` always occur after a certain amount of adversarial example generated.  But use run_single_threaded, the code works fine. More detail left in https://github.com/QData/TextAttack/pull/406

**Comment by lethaiq** [comment]
@Opdoop I was facing the same error `segmentation fault` when running on Google Colab. However, I reset the environment and install only `textattack` and it works fine. So, this is might due to some conflicts between libraries? You can try a new conda environment and just install each library one by one to see if this works.

**Comment by Opdoop** [comment]
@lethaiq Thanks a lot~ Reset environment and `segmentation fault` just go away.

**Comment by lethaiq** [comment]
> @lethaiq Thanks a lot~ Reset environment and `segmentation fault` just go away.

great

**Comment by srujanjoshi** [comment]
This issue seems to be dealt with in PR https://github.com/QData/TextAttack/pull/428

**Comment by zhy605420954** [comment]
I have a trouble like this
when I want to use gpu with **--parallel**
The console print **Successfully opened dynamic library cudart64_110.dll**
but there will be an Exception like this
**Exception: Found no GPU on your system. To run attacks in parallel, GPU is required**
I do not know how to solve it,can you help me.
