### ISSUE TITLE
Could not import CLAREAugmenter from textattack.augmentation

### ISSUE THREAD

**Issue by GMouYes** [QData/TextAttack#398]
**Describe the bug**
Hello, I encountered a problem with importing CLAREAugmenter. So far I have successfully imported and used all other augmenters as mentioned in the document, however failed on this one. I have no idea why am I failing on this specific augmenter, any ideas?

**To Reproduce**
1. from textattack.augmentation import CLAREAugmenter

**Screenshots or Traceback**
Traceback (most recent call last):
  File "\<stdin\>", line 1, in <module>
ImportError: cannot import name 'CLAREAugmenter' from 'textattack.augmentation' (/home/XXXX/anaconda3/lib/python3.7/site-packages/textattack/augmentation/__init__.py)

the XXXX is my username

**System Information (please complete the following information):**
I have python 3.7.6 cuda 10.1 on Ubuntu 18.04.4 LTS. 
textattack version 0.2.14
tensorflow version 2.3.1
torch version 1.4.0
transformers version 3.3.0

**Comment by Hanyu-Liu-123** [comment]
Hi GMouYes,

What I think caused the problem is that you're using textattack version 0.2.14, which was released on Nov 18. We added the CLARE augmenter after that release so version 0.2.14 doesn't have the CLARE augmenter.

So one way to use the CLARE augmenter is to download the current master branch and start from there. Otherwise, when a new release comes out you should be able to run the CLARE augmenter without any trouble.

Hope this could help you! Happy holidays!

**Comment by jinyongyoo** [comment]
@GMouYes Hi the newest version has been released. Please run `pip install --upgrade textattack` to run CLARE attack.
