### ISSUE TITLE
Can't import EmbeddingAugmenter in windows 10

### ISSUE THREAD

**Issue by nadavbeno** [QData/TextAttack#424]
After installing the package (from pip install or from setup.py)
I have the following python code:
`from textattack.augmentation import WordNetAugmenter, EmbeddingAugmenter, EasyDataAugmenter, CharSwapAugmenter`

but I get an error:
Exception: Could not find word_embeddings\paragramcf on server.

I tried to clear the cache but nothing helps.
What can I do?

**Comment by shensmobile** [comment]
It's because os.path.join is joining the download link for S3 using mixed slashes.  You'll see in the terminal the following statement before the error:

`textattack: Downloading https://textattack.s3.amazonaws.com/word_embeddings\paragramcf.`

The mis-matching slash before paragramcf will cause the download to fail.  I fixed this by adding `.replace("\\","/")` after the os.path.join() command in word_embeddings.py on line 274.

It's a hacky fix but it'll get you going :)

**Comment by Hanyu-Liu-123** [comment]
I think this issue has been fixed by pull request #461 so it will be closed.
