### ISSUE TITLE
When augmenting, extra quotation marks are added automatically

### ISSUE THREAD

**Issue by akkarimi** [QData/TextAttack#431]
I'm trying to augment some data using the augmentation methods (charswap, clare, wordnet, etc).
In the augmented file, however, I see that whenever there was a quotation mark in the original text, the augmenter has put other extra quotation marks. For example the following is the result of applying wordnet attack:

Original sentence: I have in the past gotten superfine sandpaper and "fixed" the edges by rounding them off.
Augmented: I have in the past perplex superfine sandpaper and "fixed"" the edges by rounding them off."

In the output file, the extra quotation marks are added to both the original sentence and the augmented one.

**Comment by Hanyu-Liu-123** [comment]
Hi akkarimi, the extra quotation marks are due to the complexity of the CSV library in handling double quotation marks. Unfortunately due to the ambiguity in CSV file formats we still need to use that library if we want to operate on CSV files. 

There're a few ways to work-around this issue:

  1. Substitute double quotation marks with single quotation marks
  2. Instead of reading from a CSV file, augment with string directly

We'll also update the augmenter so that by default, when double quotation marks are detected, they will be replaced with single quotation marks to insure augmentation runs normally.

**Comment by qiyanjun** [comment]
@Hanyu-Liu-123 I believe this is solved. Which PR?

**Comment by Hanyu-Liu-123** [comment]
I checked the main branch but the fix doesn't seem to be there. I remember creating a pull request but maybe deleted it by mistake. I'll fix the issue up by this week.

> @Hanyu-Liu-123 I believe this is solved. Which PR?

**Comment by srujanjoshi** [comment]
Issue closed because there is a corresponding Pull Request in the works.
