### ISSUE TITLE
Can I use the latest versions of tensorflow and torch?

### ISSUE THREAD

**Issue by yananchen1989** [QData/TextAttack#481]
Hello, I am using TextAttack in my project which requires the latest versions of tensorflow and torch(tf:2.3.1  torch:1.9.1).
However, I find that in TextAttack' requirements, the torch version is set to 1.7.1, which is not the latest version.
So can I use the latest versions of tensorflow and torch while using TextAttack ?

**Comment by jxmorris12** [comment]
Hi @yananchen1989 -- we depend on the [flair](https://github.com/flairnlp/flair) NLP package, which doesn't yet support torch >= 1.8.0, causing this whole mess of dependencies. We know this can be frustrating, sorry. We're working on removing this flair dependency so that we can upgrade all of our packages.

for now, please try to create a textattack-dependent virtual env so you don't have to worry about these things!

**Comment by jxmorris12** [comment]
(Oh, I might add that you can try just upgrading torch/tf and see if flair breaks behind the scenes. It very likely won't.)

**Comment by jinyongyoo** [comment]
The issue with Flair was that pytorch 1.8 broke backward compatibility with previously trained LSTM models. This issue has been fixed with Pytorch 1.9. As long people do not use Pytorch 1.8, there is should be no issue. I requested to the Flair developers to update their requirements and make a new release (https://github.com/flairNLP/flair/issues/2137). They did update their requirements but haven't made a new release yet so I'll ask again.
