### ISSUE TITLE
Why only attack positive samples？

### ISSUE THREAD

**Issue by YiLiuHFUT** [QData/TextAttack#562]
When I used the IMDB data set, I found that I used several attack methods in textattack. If it encounters negative, it will skip, and it will attack when it encounters positive. As a result, the labels of the final adversarial samples are all 0. (1to0), why is this?

**Comment by donggrant** [comment]
This is probably just a limitation on generating adversarial examples for certain binary classification tasks. I assume that it's a lot harder to make a negative example positive through perturbations for most contexts. But this is probably something that should be considered for improvement. Can you list the attack methods that show this behavior?

**Comment by gallilmaimon** [comment]
This happens for all attacks (such as textfooler and PWWS). The reason it skips the negatively classified input texts is because they are labeled positive, and wrongly classified as negative (and the attacks skip already wrongly classified texts).

All the samples are positive because IMDB dataset is sorted by labels and the '--num-examples' flag only takes the first samples.

However, it would be useful to support natively a way to take a mixed subset, and I couldn't find a way to do this (the 'shuffle' option only seems to shuffle the already selected texts)

**Comment by YiLiuHFUT** [comment]
Thank you for your answer！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QData/TextAttack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 下午5:06
***@***.***&gt;;
抄送:&nbsp;"171305116 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [QData/TextAttack] Why only attack positive samples？ (Issue #562)





 
This happens for all attacks (such as textfooler and PWWS). The reason it skips the negatively classified input texts is because they are labeled positive, and wrongly classified as negative (and the attacks skip already wrongly classified texts).
 
All the samples are positive because IMDB dataset is sorted by labels and the '--num-examples' flag only takes the first samples.
 
However, it would be useful to support natively a way to take a mixed subset, and I couldn't find a way to do this (the 'shuffle' option only seems to shuffle the already selected texts)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
