### ISSUE TITLE
Adversarial perturbations exceed max_percent values in overlap constraint

### ISSUE THREAD

**Issue by salijona** [QData/TextAttack#626]
I run an attack using FasterGeneticAlgorithmJia2019 recipe which has the maximum perturbation  set to **20%** through max_percent=0.2
However some of the generated adversarial examples for the rotten_tomatoes dataset pass this threshold. 

Below two examples: 

**Example A:** 

Original sentence: throws in [[enough]] [[clever]] and unexpected twists to make the formula [[feel]] fresh ."
Adversarial sentence: "throws in [[rather]] [[brainy]] and unexpected twists to make the formula [[think]] fresh .

Percentage of modified words: **21.4%**

**Example B:** 
Original sentence: it may not be [[particularly]] [[innovative]] , but the film's [[crisp]] , [[unaffected]] [[style]] and air of [[gentle]] [[longing]] make it [[unexpectedly]] [[rewarding]] .

Adversarial sentence: it may not be [[specifically]] [[innovator]] , but the film's [[crunchy]] , [[undamaged]] [[styling]] and air of [[mild]] [[homesickness]] make it [[abruptly]] [[rewards]] .

Percentage of modified words: **37.5%**

**Comment by jxmorris12** [comment]
@salijona thanks for reporting! I'm not sure how this is misbehaving, but it seems the `MaxWordsPerturbed` constraint isn't working properly with `max_percent` set. It does round up, which is probably the case for Example A, but Example B seems totally off so I don't know offhand what's going wrong.

If this is a blocker for you, maybe you could try the `MaxModificationRate` constraint, which does the same thing. 

(As an aside, we should probably remove the percent option from `MaxNumWords` in favor of `MaxModificationRate`. No reason to have two ways to do the same thing.)

**Comment by VijayKalmath** [comment]
@salijona  , Can you share the textattack command where in you saw this behavior ? If you were not using cli , please share the code or a link to the colab notebook.

**Comment by VijayKalmath** [comment]
Tried to debug this Issue , 

TextAttack Command Used : 

```
textattack attack --recipe faster-alzantot  \ 
                                 --num-examples-offset 47 --num-examples 1 \
                                   --model xlnet-base-cased-mr
```

The following sentence is the 47th Index in the rotten tomatoes datasets. 

it may not be [[particularly]] [[innovative]] , but the film's [[crisp]] , [[unaffected]] [[style]] and air of [[gentle]] [[longing]] make it [[unexpectedly]] [[rewarding]] .

I forced the transformation by replacing the following function 
https://github.com/QData/TextAttack/blob/d13575cedde5c4ba6c253f24c0a3ff0335ccd24e/textattack/transformations/word_swaps/word_swap.py#L40

with the following code : 

```

        # >>>> DEBUGGING CODE >>>>
        indices_to_modify = {4,5,9,10,11,15,16,19,20}
        replacement_dict = { 4 : "specifically" , 5: "innovator" , 9: "crunchy" , 10: "undamaged" , 11: "styling" , 15: "mild" , 16: "homesickness" , 19:"abruptly", 20:"rewards"}
        text=current_text
        transformed_texts_idx = [] 
        transformed_texts = []
        for i in indices_to_modify : 
            text = text.replace_word_at_index(i, replacement_dict[i])
        transformed_texts_idx.append(text)
        transformed_texts.extend(transformed_texts_idx)
        retruns transformed_texts
```

The AttackedText always seems to get filtered and is never chosen as the final result which is the expected behaviour. 

I tested the same setup for all the rotten-tomatoes trained models in the Model Zoo. 


@jxmorris12  Can you add in your thoughts on how to proceed with this Issue.

**Comment by jxmorris12** [comment]
@salijona please open if you can provide us a reproducible case.
