### ISSUE TITLE
Generating multiple adversarial examples 

### ISSUE THREAD

**Issue by ashim95** [QData/TextAttack#666]
Hi,

Quick question, Does the library support generating multiple adversarial examples per original training example? If not, how straightforward should it be to implement this?

Thanks,

**Comment by VijayKalmath** [comment]
Hello @ashim95 , 

The library does support generating multiple adversarial examples in the Augmenter Class with a flag called `high_yield` in AugmenterArgs, you can find more about it here [TextAttack Augmentation](https://textattack.readthedocs.io/en/master/2notebook/3_Augmentations.html?highlight=high_yield)

**Comment by jxmorris12** [comment]
@ashim95 - this is a really good suggestion, thanks for the feedback! 

First, @VijayKalmath is totally right, you can generate many augmentations of a single example using our augmentation API.

Second: in terms of generating multiple adversarial examples. This feature is not currently supported, and the problem isn't that well-defined. Would you want to just continue the search after finding a single one, and repeat until you find `n` examples that fool the model? If you do this, you're likely to find `n` very similar/highly-correlated examples. In fact, they will all just be additional transformations of the first one. How useful is this? What do you need it for?

That said, it wouldn't be trivial to add this feature to the library, though it wouldn't be that difficult. We'd have to modify all of the search methods to iterate until `n` adversarial examples have been found, instead of a single one. Then we can just count each new thing as a separate `AttackResult`. This change would probably have some downstream effects like in the way metrics are computed. And there are probably other second-order effects that I can't think of right now.

But maybe another way to implement this feature would be a new search method. It could look something like beam search, except look for the `n` *most different* examples that still fool the model. I'm not exactly sure how to do it, but this sounds more interesting than the first way. Again, it all depends on what you want this feature for in the first place. And you'd still need to change the API a bit to accommodate search methods that return multiple adversarial examples, instead of assuming they return a single one.

**Comment by ashim95** [comment]
Thanks @jxmorris12 and @VijayKalmath for the suggestions. 

@jxmorris12 I agree, simply saying I want `n` adversarial examples is not a well-defined thing. What I want to study is the effect of using multiple adversarial examples during adversarial training for improving the robustness. And then like you said, it's an open question: Should you add multiple similarly perturbed examples or should you add very different looking examples? 

If I choose to implement such a feature in TextAttack, I will be happy to send in a pull request (assuming it doesn't require a lot of changes in the codebase). 

Thanks again for the suggestions.

**Comment by jxmorris12** [comment]
Ok, awesome! Thanks for the thoughtful response @ashim95. Let me know what you end up doing.
